version: '3.8'

services:
  control-plane-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  data-plane-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATA_PLANE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATA_PLANE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATA_PLANE_POSTGRES_DB}
    ports:
      - "5433:5432"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  vault:
    image: vault:1.9.0
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_ADDR: ${VAULT_ADDR}
